---
version: "3.8"

services:
  database:
    container_name: database
    environment:
      POSTGRESQL_USER: default
      POSTGRESQL_PASSWORD: default
      POSTGRESQL_DATABASE: default
    hostname: database
    image: postgres:12
    restart: always
    volumes:
      - ./.volumes/database:/pgdata:z

  backend:
    container_name: backend
    entrypoint:
      - "sh"
      - "-c"
      - "npm ci && npm run start"
    environment:
      NODE_ENV: development
      PGHOST: database
      PGUSER: default
      PGPASSWORD: default
      PGDATABASE: default
    hostname: backend
    image: node:14
    links:
      - database
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app:z
      - ./.cache/backend/node_modules:/app/node_modules:z
    working_dir: "/app"

  frontend:
    container_name: frontend
    entrypoint:
      - "sh"
      - "-c"
      - "npm ci && npm run start"
    environment:
      NODE_ENV: development
      BACKEND_URL: backend
    hostname: frontend
    image: node:14
    links:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - ./.cache/frontend/node_modules:/app/node_modules:z
    working_dir: "/app"
