apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: frontend
      deployment: quickstart-openshift-2286-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quickstart-openshift-2286
        component: frontend
        deployment: quickstart-openshift-2286-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - quickstart-openshift-2285-frontend
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - quickstart-openshift-2285
      containers:
      - env:
        - name: BACKEND_URL
          value: https://quickstart-openshift-2286-backend.apps.silver.devops.gov.bc.ca:443
        - name: LOG_LEVEL
          value: info
        image: ghcr.io/bcgov/quickstart-openshift/frontend:2286
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: quickstart-openshift-2286-frontend
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-20T17:31:40Z"
    lastUpdateTime: "2025-02-20T17:31:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-20T17:31:29Z"
    lastUpdateTime: "2025-02-20T17:31:40Z"
    message: ReplicaSet "quickstart-openshift-2286-frontend-77755c9c48" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
