apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: quickstart-openshift-2285
      app.kubernetes.io/name: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "3003"
        prometheus.io/scrape: "true"
        rollme: IhiFe
      creationTimestamp: null
      labels:
        app.kubernetes.io/image-version: "2285"
        app.kubernetes.io/instance: quickstart-openshift-2285
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: frontend
        app.kubernetes.io/short-name: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - quickstart-openshift-2285-frontend
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - quickstart-openshift-2285
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: BACKEND_URL
          value: http://quickstart-openshift-2285-backend
        - name: LOG_LEVEL
          value: info
        image: ghcr.io/bcgov/quickstart-openshift/frontend:2285
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: quickstart-openshift-2285-frontend
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-19T01:34:41Z"
    lastUpdateTime: "2025-02-19T01:34:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-19T01:34:33Z"
    lastUpdateTime: "2025-02-19T01:34:41Z"
    message: ReplicaSet "quickstart-openshift-2285-frontend-b77778958" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
