apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Greenfield Pipeline"
    tags: "gfp"
    iconClass: icon-js
labels:
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: App name
    value: gfp
  - name: SUFFIX
    description: Deployment suffix, e.g. pr number or prod
    required: true
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      lookupPolicy:
        local: false
      tags:
      - name: pr-${SUFFIX}
        from:
          kind: DockerImage
          name: ghcr.io/bcgov-nr/greenfield-pipeline:pr-${SUFFIX}
        referencePolicy:
          type: Local
