apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Greenfield Pipeline"
    tags: "gfp"
    iconClass: icon-js
labels:
  app.kubernetes.io/part-of: "${NAME}"
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Module name
    value: gfp
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-### or prod
    required: true
  - name: ENV
    description: Environment, e.g. dev, test, prod
    required: true
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CPU_REQUEST
    value: 250m
  - name: MEMORY_REQUEST
    value: 1Gi
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        name: ${NAME}-${SUFFIX}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            name: ${NAME}-${SUFFIX}
        spec:
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/245e18-dev/${NAME}-${SUFFIX}:latest
              imagePullPolicy: Always
              name: ${NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                httpGet:
                  path: /api/
                  port: 3000
                  scheme: HTTP
                # first probe will fire some time between:
                # initialDelaySeconds and initialDelaySeconds + periodSeconds
                initialDelaySeconds: 30
                periodSeconds: 120
                timeoutSeconds: 1
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /api/
                  port: 3000
                  scheme: HTTP
                # first probe will fire some time between:
                # initialDelaySeconds and initialDelaySeconds + periodSeconds
                initialDelaySeconds: 30
                periodSeconds: 120
                timeoutSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      ports:
        - name: 3000-tcp
          protocol: TCP
          port: 8080
          targetPort: 3000
      selector:
        name: ${NAME}-${SUFFIX}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${SUFFIX}
      name: ${NAME}-${SUFFIX}
    spec:
      host: ${NAME}-${SUFFIX}-${ENV}.${DOMAIN}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}-${SUFFIX}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
