apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Greenfield Template"
    tags: "gfp"
    iconClass: icon-js
labels:
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Product name
    value: gfp
  - name: COMPONENT
    description: Component name
    value: database
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-### or prod
    required: true
  - description: Password for the PostgreSQL connection user.
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: PG_PASSWORD
  - description: Volume space available for data, e.g. 512Mi, 2Gi.
    displayName: Database Volume Capacity
    name: DB_VOLUME_CAPACITY
    required: true
    value: 1Gi
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${COMPONENT}-${SUFFIX}
      labels:
        app: ${NAME}-${SUFFIX}
    stringData:
      database-name: "${NAME}"
      database-password: "${PG_PASSWORD}"
      database-user: "${NAME}"
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}-${COMPONENT}-${SUFFIX}
      labels:
        app: ${NAME}-${SUFFIX}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${DB_VOLUME_CAPACITY}"
      storageClassName: netapp-file-standard
