apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Greenfield Template"
    tags: "gfp"
    iconClass: icon-js
labels:
  app.kubernetes.io/part-of: "${NAME}-${SUFFIX}"
  app: ${NAME}-${SUFFIX}
parameters:
  - name: NAME
    description: Product name
    value: gfp
  - name: COMPONENT
    description: Component name
    value: database
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-### or prod
    required: true
  - description: Password for the PostgreSQL connection user.
    from: "[a-zA-Z0-9]{16}"
    generate: expression
    name: PG_PASSWORD
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${COMPONENT}-${SUFFIX}
    stringData:
      database-name: "${NAME}"
      database-password: "${PG_PASSWORD}"
      database-user: "${NAME}"
