# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

id: |-
  {{- printf "%s-%s-%s" .Values.repo (.Values.zone | toString) .Values.database.component }}

repo: ~
zone: ~

database:
  component: database
  name: default
  user: default
