apiVersion: v1
kind: Template
metadata:
  name: vault-sync-secrets-job
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: my-secret
  type: Opaque
  data:
    OC_TOKEN: <base64-encoded-username>
    password: <base64-encoded-password>
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: vault-sync-job
  spec:
    template:
      spec:
        containers:
        - name: main-container
          image: my-main-container-image
          env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
        restartPolicy: Never
parameters:
- name: USERNAME
  description: "The username for the secret"
  required: true
- name: PASSWORD
  description: "The password for the secret"
  required: true