apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    openshift.io/display-name: "Backend Deployment Template"
    description: "Template for deploying the backend component with database migrations, networking, scaling, and security configurations."
    tags: "backend,nodejs,postgresql,flyway,quickstart"
    iconClass: "icon-nodejs"
    openshift.io/documentation-url: "https://github.com/bcgov/quickstart-openshift"
    openshift.io/provider-display-name: "BC Government"
parameters:
  - name: NAME
    description: "Application name, used to group and identify resources"
    required: true
    value: quickstart
  - name: COMPONENT
    description: "Component identifier within the application (backend)"
    value: "backend"
  - name: ZONE
    description: "Deployment zone (e.g. dev, test, prod, pr-###). Used for resource isolation"
    required: true
    pattern: "^(test|demo|prod|[0-9]{1,4})$"
  - name: NAMESPACE
    description: "OpenShift namespace"
    required: true
    pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" 
  - name: POSTGRES_PASSWORD
    description: "Postgres database password"
    required: true
  - name: POSTGRES_USER
    description: "Postgres database user"
    required: true
  - name: POSTGRES_DATABASE
    description: "Postgres database name"
    required: true
  - name: POSTGRES_HOST
    description: "Postgres database host"
    required: true
  - name: FLYWAY_BASE_URL
    description: "Flyway database URL without database name"
    value: "jdbc:postgresql://postgres-crunchy-primary.${NAMESPACE}.svc:5432"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}-${ZONE}-backend
    labels:
        app: "${NAME}-${ZONE}"
        component: "${COMPONENT}"
  data:
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_USER: ${POSTGRES_PASSWORD}
    POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    POSTGRES_HOST: ${POSTGRES_HOST}

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}-${ZONE}-flyway
    labels:
        app: "${NAME}-${ZONE}"
        component: "${COMPONENT}"
  data:
    FLYWAY_URL: ${FLYWAY_BASE_URL}/${POSTGRES_DATABASE}
    FLYWAY_USER: ${POSTGRES_USER}
    FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}-${ZONE}-database
    labels:
        app: "${NAME}-${ZONE}"
        component: "${COMPONENT}"
  data:
    dbname: ${POSTGRES_DATABASE}
    host: postgres-crunchy-primary.${NAMESPACE}.svc
    jdbc-uri: "jdbc:postgresql://postgres-crunchy-primary.${NAMESPACE}.svc:5432/${POSTGRES_DATABASE}?password=c1J5_%3D20LG-ABt%5Bd28%3BmM2Ba&user=${POSTGRES_DATABASE}"
    password: ${POSTGRES_PASSWORD}
    port: 5432
    user: ${POSTGRES_USER}
    uri: "postgresql://${POSTGRES_DATABASE}:c1J5_=20LG-ABt%5Bd28;mM2Ba@postgres-crunchy-primary.${NAMESPACE}.svc:5432/${POSTGRES_DATABASE}"
    pgbouncer-host: "postgres-crunchy-pgbouncer.${NAMESPACE}.svc"
    pgbouncer-jdbc-uri: "postgresql://${POSTGRES_DATABASE}:c1J5_=20LG-ABt%5Bd28;mM2Ba@postgres-crunchy-pgbouncer.${NAMESPACE}.svc:5432/${POSTGRES_DATABASE}"
    pgbouncer-port: 5432
    pgbouncer-uri: "jdbc:postgresql://postgres-crunchy-primary.${NAMESPACE}.svc:5432/${POSTGRES_DATABASE}?password=c1J5_%3D20LG-ABt%5Bd28%3BmM2Ba&user=${POSTGRES_DATABASE}"
    verifier: SCRAM-SHA-256$4096:LCaagN42kqMM0vV3nY+UkQ==$T3zTbTWcriWu6DHXPR71UteTUv07SJ3mzNCYZPXe0yM=:CalCQWvL+6aayivhNIYoFWlI8LiuUtd26duut/wXOsQ=
