---
{{- if and .Values.configmap .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "component.fullname" . }}
  labels:
    {{- include "component.labels" . | nindent 4 }}
data:
    {{- range  .Values.configmap.data }}
    {{ .name | quote }}: {{ .value | quote }}
    {{- end }}

{{- end }}
