{{- $name := printf "%s-%s-%s" .Values.repo (.Values.zone | toString) .Values.database.component }}
{{- $label := printf "%s-%s" .Values.repo (.Values.zone | toString) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.pvc.size }}
  storageClassName: netapp-file-standard
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ $name }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: {{ $name }}
      from:
        kind: DockerImage
        name: "{{ .Values.image.registry }}/{{ .Values.org }}/{{ .Values.repo }}/{{ .Values.component }}:{{ .Values.image.tag }}"
      referencePolicy:
        type: Local
---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ $name }}
spec:
  replicas: 1
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ $name }}
        from:
          kind: ImageStreamTag
          name: "{{ $name }}:{{ .Values.image.tag }}"
  selector:
    deploymentconfig: {{ $name }}
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    activeDeadlineSeconds: 21600
  template:
    metadata:
      name: {{ $name }}
      labels:
        app: {{ $label }}
        deploymentconfig: {{ $name }}
    spec:
      volumes:
        - name: {{ $name }}
          persistentVolumeClaim:
            claimName: {{ $name }}
      containers:
        - name: {{ $name }}
          image: "{{ $name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /usr/bin/env
                - bash
                - -c
                - psql -q -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
                - /usr/bin/env
                - bash
                - -c
                - psql -q -U $POSTGRES_USER -d $POSTGRES_DB -c 'SELECT 1'
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 1
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ $name }}
                  key: database-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $name }}
                  key: database-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $name }}
                  key: database-user
          volumeMounts:
            - name: {{ $name }}
              mountPath: {{ .Values.resources.pvc.mount }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  ports:
    - name: postgresql
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    deploymentconfig: {{ $name }}
  sessionAffinity: None
  type: ClusterIP
