name: .Merge

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semver:
    name: Semantic Version
    outputs:
      tag: ${{ steps.semver.outputs.tag }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v4
        id: semver
        with:
          git-branch: refs/heads/${{ github.head_ref }}
          git-push: "false"
          github-token: ${{ github.token }}
          skip-commit: "true"
          skip-on-empty: "false"
          skip-version-file: "true"

      - name: Create Tags
        if: ${{ steps.semver.outputs.tag != '' }}
        run: |
          git tag ${{ steps.changelog.outputs.tag }}
          git push origin --tag

  deploys-test:
    name: Deploys (test)
    if: ${{ steps.semver.outputs.tag != '' }}
    needs: [semver]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      tag: test
      target: test

  integration-e2e:
    name: Integration and E2E Tests
    needs: [deploys-test]
    uses: ./.github/workflows/.tests.yml
    with:
      target: test

  deploys-prod:
    name: Deploys (prod)
    needs: [integration-e2e]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      tag: test
      target: prod

  tag-images:
    name: Tag Images
    needs: [deploys-prod]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 2
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: test
          tags: prod
