name: Build Image

on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
        description: Component (backend, frontend)
      img_build:
        type: string
        required: true
        description: Default zone (pr#, test, demo, prod)
      img_fallback:
        type: string
        required: true
        description: Where to pull default images from (prod, pr#, test)
      triggers:
        type: string
        required: true
        description: Build triggers in a bash array, e.g. ('./backend/', './frontend/)
    secrets:
      gh_token:
        required: true
        description: Default github token (secrets.GITHUB_TOKEN)
    outputs:
      build:
        description: True = build has changed
        value: ${{ jobs.check.outputs.build }}

jobs:
  # Check triggers to see if a build is required
  # Returns jobs.check.outputs.build as a boolean (true/false)
  check:
    name: ${{ inputs.component }} check
    uses: ./.github/workflows/_build-check.yml
    with:
      triggers: ${{ inputs.triggers }}

  # If a build is not required, reuse a previous image
  retag:
    name: ${{ inputs.component }} retag
    needs:
      - check
    if: needs.check.outputs.build != 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Recycle/retag Previous Images
        uses: shrink/actions-docker-registry-tag@v2
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          target: ${{ inputs.img_fallback }}-${{ inputs.component }}
          tags: |
            ${{ inputs.img_build }}-${{ inputs.component }}

  # If a build is required, then create a new image
  build:
    name: ${{ inputs.component }} build
    needs:
      - check
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.gh_token }}

      - name: Build and push ${{ inputs.component }} Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ inputs.component }}/
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.img_build }}-${{ inputs.component }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
