name: Build Image

on:
  workflow_call:
    inputs:
      component:
        type: string
        required: true
        description: Component (backend, frontend)
      zone:
        type: string
        required: true
        description: Default zone (pr#, test, demo, prod)

env:
  registry: ghcr.io
  name: gfp

jobs:
  build:
    name: ${{ inputs.component }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ inputs.component }} Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ inputs.component }}/
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:${{ inputs.zone }}-${{ inputs.component }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
