name: Dump Contexts

on:
  pull_request:
  push:

jobs:
  dump:
    name: Dump GitHub Context
    runs-on: ubuntu-22.04
    steps:
      - name: Dump GitHub Context
        run: echo "${{ toJson(github) }}"
