name: Merge

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.graphics/**'
      - '.github/**'
      - '!.github/workflows/merge.yml'

jobs:
  semver:
    name: Semantic Version and Tag
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      # Outputs semver as steps.id.outputs.tag
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v4
        id: changelog
        with:
          git-branch: refs/heads/${{ github.event.repository.default_branch }}
          git-push: "false"
          github-token: ${{ github.token }}
          skip-commit: "true"
          skip-on-empty: "false"
          skip-version-file: "true"

      # Create tag and output semver
      - name: Create Tags
        run: |
          echo git tag ${{ steps.changelog.outputs.tag }}
          echo git push origin --tag

  # Get PR number, assmuing a PR was merged
  pr-number:
    name: Get PR Number
    runs-on: ubuntu-22.04
    steps:
      - run: |
          # Get PR number from commit message
          PR_NO=$(echo ${{ github.event.head_commit.message }} | \
            jq .head_commit.message | cut -d'#' -f 2 | cut -d')' -f 1)
          echo "$pr={PR_NO}" >> $GITHUB_OUTPUT

  # Add tag number and latest tags to PR image
  retags:
    name: Retag Images
    needs: [semver, pr-number]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.pr-number.outputs.pr }}
          tags: |
            latest
            ${{ needs.semver.outputs.tag }}

  deploy-test:
    name: Deploy (test)
    needs: [pr-number]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      environment: test
      tag: ${{ github.event.number }}
      release: test

  integration-e2e:
    name: Integration and E2E Tests
    needs: [deploy-test]
    uses: ./.github/workflows/.tests.yml
    with:
      target: test

  deploy-prod:
    name: Deploy (prod)
    needs: [integration-e2e, pr-number]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      environment: prod
      tag: ${{ needs.pr-number.outputs.pr }}
      release: prod

  promote:
    name: Promote Images
    needs: [deploy-prod, pr-number]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.pr-number.outputs.pr }}
          tags: prod
