name: Merge

on:
  push:
    tags: ['*']

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploys-test:
    name: Deploys (test)
    needs: [get-digest]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      environment: test
      backend_tag: ${{ github.event.release.tag_name }}
      migrations_tag: ${{ github.event.release.tag_name }}
      frontend_tag: ${{ github.event.release.tag_name }}
      target: test

  integration-e2e:
    name: Integration and E2E Tests
    needs: [deploys-test]
    uses: ./.github/workflows/.tests.yml
    with:
      target: test

  deploys-prod:
    name: Deploys (prod)
    needs: [get-digest, integration-e2e]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      environment: prod
      backend_tag: ${{ github.event.release.tag_name }}
      migrations_tag: ${{ github.event.release.tag_name }}
      frontend_tag: ${{ github.event.release.tag_name }}
      target: prod
