name: Merge to Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/*"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  tests:
    name: Unit Tests
    uses: bcgov/nr-quickstart-helpers/.github/workflows/_unit-tests.yml@v0.0.2
    strategy:
      matrix:
        component: [backend, frontend]
    with:
      component: ${{ matrix.component }}
      test_cmd: npm run test:cov

  sonarcloud-backend:
    name: Static Analysis Backend
    needs:
      - tests
    runs-on: ubuntu-22.04
    steps:
      # Disable shallow clone for SonarCloud analysis
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Backend coverage from cache
        uses: actions/cache@v3
        with:
          path: backend/coverage
          key: coverage-backend-${{ github.run_number }}
          restore-keys: |
            coverage-backend-

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          # Needed to get PR information, if any
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.cobertura.reportPaths=coverage/cobertura-coverage.xml
            -Dsonar.exclusions=**/test/**,.github/**/*,*.md
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.project.monorepo.enabled=true
            -Dsonar.projectKey=bcgov_nr-quickstart-typescript_backend
            -Dsonar.tests=test

  sonarcloud-frontend:
    name: SonarCloud Frontend
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      # Disable shallow clone for SonarCloud analysis
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Backend coverage from cache
        uses: actions/cache@v3
        with:
          path: backend/coverage
          key: coverage-backend-${{ github.run_number }}
          restore-keys: |
            coverage-backend-

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.cobertura.reportPaths=coverage/cobertura-coverage.xml
            -Dsonar.exclusions=**/test/**,.github/**/*,*.md
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.project.monorepo.enabled=true
            -Dsonar.projectKey=bcgov_nr-quickstart-typescript_frontend
            -Dsonar.tests=test

  deploys-test:
    name: TEST Deployments
    needs:
      - codeql
    uses: bcgov/nr-quickstart-helpers/.github/workflows/_deploy.yml@v0.0.2
    strategy:
      matrix:
        component: [backend, database, frontend]
        include:
          - component: database
            overwrite: false
            template_file: database/openshift.deploy.yml
            template_vars: -p ZONE=test -p NAME=${{ github.event.repository.name }}
          - component: backend
            overwrite: true
            template_file: backend/openshift.deploy.yml
            template_vars:
              -p ZONE=test -p PROMOTE=${{ github.repository }}/backend:test
              -p NAME=${{ github.event.repository.name }}
          - component: frontend
            overwrite: true
            template_file: frontend/openshift.deploy.yml
            template_vars:
              -p ZONE=test -p PROMOTE=${{ github.repository }}/frontend:test
              -p NAME=${{ github.event.repository.name }}
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_server: ${{ secrets.OC_SERVER }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      component: ${{ matrix.component }}
      environment: test
      overwrite: ${{ matrix.overwrite }}
      penetration_test: true
      repository: bcgov/nr-quickstart-typescript
      template_file: ${{ matrix.template_file }}
      template_vars: ${{ matrix.template_vars }}

  # https://github.com/marketplace/actions/aqua-security-trivy
  trivy-repo:
    name: Repository Report
    needs:
      - deploys-test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.8.0
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          security-checks: "vuln,secret,config"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"

  deploys-prod:
    name: PROD Deployments
    needs:
      - trivy-repo
    uses: bcgov/nr-quickstart-helpers/.github/workflows/_deploy.yml@v0.0.2
    strategy:
      matrix:
        component: [backend, database, frontend]
        include:
          - component: database
            overwrite: false
            template_file: database/openshift.deploy.yml
            template_vars: -p ZONE=prod -p NAME=${{ github.event.repository.name }}
          - component: backend
            overwrite: true
            template_file: backend/openshift.deploy.yml
            template_vars:
              -p ZONE=prod -p PROMOTE=${{ github.repository }}/backend:test
              -p NAME=${{ github.event.repository.name }}
          - component: frontend
            overwrite: true
            template_file: frontend/openshift.deploy.yml
            template_vars:
              -p ZONE=prod -p PROMOTE=${{ github.repository }}/frontend:test
              -p NAME=${{ github.event.repository.name }}
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_server: ${{ secrets.OC_SERVER }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      component: ${{ matrix.component }}
      environment: prod
      overwrite: ${{ matrix.overwrite }}
      penetration_test: true
      repository: bcgov/nr-quickstart-typescript
      template_file: ${{ matrix.template_file }}
      template_vars: ${{ matrix.template_vars }}

  image-promotions:
    name: Promote images to PROD
    needs:
      - deploys-prod
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        component: [backend, frontend]
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.component }}
          target: test
          tags: prod
