name: Merge

on:
  pull_request:
  # workflow_run:
  #   workflows: [PR Closed]
  #   types: [completed]
  # workflow_dispatch:

jobs:
  semver:
    name: Semantic Version
    outputs:
      tag: ${{ steps.semver.outputs.tag }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v4
        id: semver
        with:
          git-branch: refs/heads/${{ github.event.repository.default_branch }}
          git-push: "false"
          github-token: ${{ github.token }}
          skip-commit: "true"
          skip-on-empty: "false"
          skip-version-file: "true"

      - name: Create Tags
        if: ${{ steps.semver.outputs.tag != '' }}
        run: |
          git tag ${{ steps.changelog.outputs.tag }}
          git push origin --tag

  deploy-test:
    name: Deploy (test)
    if: ${{ needs.semver.outputs.tag != '' }}
    needs: [promote-test, semver]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      environment: test
      tag: test
      target: test

  integration-e2e:
    name: Integration and E2E Tests
    needs: [deploy-test]
    uses: ./.github/workflows/.tests.yml
    with:
      target: test

  deploy-prod:
    name: Deploy (prod)
    needs: [integration-e2e]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      environment: prod
      tag: test
      target: prod

  promote-prod:
    name: Tag Images
    needs: [deploy-prod]
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 2
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: test
          tags: prod
