name: Merge

on:
  workflow_run:
    workflows: [PR Closed]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semver:
    name: Semantic Version
    outputs:
      semver: ${{ steps.changelog.outputs.version }}
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v3
        id: changelog
        continue-on-error: true
        with:
          github-token: ${{ github.token }}
          skip-version-file: 'true'
          skip-commit: 'true'
          skip-on-empty: 'false'
          git-push: 'false'

  retag-images:
    name: Tag Images
    needs: [semver]
    runs-on: ubuntu-22.04
    strategy:
        matrix:
            package: [backend, migrations, frontend]
    steps:
      - name: Tag Docker Images
        uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: test
          tags: ${{ needs.semver.outputs.semver }}

  deploys-test:
    name: Deploys (test)
    needs: [retag-images, semver]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      tag: ${{ needs.semver.outputs.semver }}
      target: test

  integration-tests:
    needs: [deploys-test]
    name: Integration Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Integration tests
        env:
          API_NAME: nest
          BASE_URL: https://${{ github.event.repository.name }}-test-frontend.apps.silver.devops.gov.bc.ca
        run: |
          cd integration-tests
          npm ci
          node src/main.js

  cypress-e2e:
    name: E2E Tests
    needs: [deploys-test]
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: cypress-io/github-action@v6
        name: Cypress run
        env:
          CYPRESS_baseUrl: https://${{ github.event.repository.name }}-test-frontend.apps.silver.devops.gov.bc.ca/
        with:
          config: pageLoadTimeout=10000
          working-directory: ./frontend
          browser: ${{ matrix.browser }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

  deploys-prod:
    name: Deploys (prod)
    needs: [cypress-e2e, integration-tests]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      tag: ${{ needs.semver.outputs.semver }}
      target: prod

  tags:
    name: Create Tags
    needs: [deploys-prod]
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - name: Create Tags
        if: ${{ needs.semver.outputs.semver != '' }}
        run: |
          git tag ${{ needs.semver.outputs.semver }}
          git push origin --tag

  cleanup:
    name: Cleanup
    environment: ${{ matrix.environment }}
    needs: [deploys-prod]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        environment: [test, prod]
    steps:
      - name: Remove OpenShift artifacts
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ vars.OC_SERVER }}
          oc project ${{ vars.OC_NAMESPACE }}

          # Remove old build runs, build pods and deployment pods
          oc delete po --field-selector=status.phase==Succeeded
