name: Merge

on:
  push:
    tags: [v*]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test for tagging
    runs-on: ubuntu-22.04
    steps:
      - name: Check Tag
        run: |
          echo "Tag: ${{ github.ref_name }}"

  # deploys-test:
  #   name: Deploys (test)
  #   uses: ./.github/workflows/.deploy.yml
  #   secrets: inherit
  #   with:
  #     tag: ${{ github.ref }}
  #     target: test

  # integration-e2e:
  #   name: Integration and E2E Tests
  #   needs: [deploys-test]
  #   uses: ./.github/workflows/.tests.yml
  #   with:
  #     target: test

  # deploys-prod:
  #   name: Deploys (prod)
  #   needs: [integration-e2e]
  #   uses: ./.github/workflows/.deploy.yml
  #   secrets: inherit
  #   with:
  #     tag: ${{ github.ref }}
  #     target: prod
