name: Cleanup

on:
  pull_request:
    types:
      - closed
    paths-ignore:
      - ".**"
      - "**.md"
      - "**.yml"
      - "**.yaml"

env:
  REGISTRY: ghcr.io
  NAME: gfp

jobs:
  # Clean up OpenShift when PR closed, no conditions
  cleanup-openshift:
    name: Cleanup OpenShift
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Remove OpenShift artifacts
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.OC_NAMESPACE }}

          # Remove old build runs, build pods and deployment pods
          oc delete all,pvc,secret -l app=${{ env.NAME }}-${{ github.event.number }}

  # If merged, then handle any image promotion
  image-backend:
    name: Backend Image Handling
    outputs:
      build: ${{ steps.check.outputs.build }}
    env:
      COMPONENT: backend
      PROMOTION: test
    environment:
      name: test
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Check and process modified files
        id: check
        run: |
          set -eux

          # Pull images and SHAs
          docker pull ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.number }}-${{ env.COMPONENT }}
          docker pull ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.PROMOTION }}-${{ env.COMPONENT }}
          SHA0=$(docker inspect -f '{{.Id}}' ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.number }}-${{ env.COMPONENT }})
          SHA1=$(docker inspect -f '{{.Id}}' ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.PROMOTION }}-${{ env.COMPONENT }})

          # If different, then trigger updates
          if [[ "${SHA0}" == "${SHA1} "]]; then
            echo "::set-output name=build::true"
            echo "Image has changed"

            # Login to OpenShift and select project
            oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
            oc project ${{ secrets.OC_NAMESPACE }}
            oc delete is/${{ env.NAME }}-${{ env.PROMOTION}}-${{ env.COMPONENT }} || true
            exit 0
          fi
          echo "Image promotion not required"

      - name: Promote Backend Image
        if: steps.check.outputs.build == 'true'
        uses: shrink/actions-docker-registry-tag@v2
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          target: ${{ github.event.number }}-${{ env.COMPONENT }}
          tags: |
            ${{ env.PROMOTION }}-${{ env.COMPONENT }}

  # If merged, then handle any image promotion
  image-frontend:
    name: Frontend Image Handling
    outputs:
      build: ${{ steps.check.outputs.build }}
    env:
      COMPONENT: frontend
      PROMOTION: test
    environment:
      name: test
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Check and process modified files
        id: check
        run: |
          set -eux

          # Pull images and SHAs
          docker pull ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.number }}-${{ env.COMPONENT }}
          docker pull ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.PROMOTION }}-${{ env.COMPONENT }}
          SHA0=$(docker inspect -f '{{.Id}}' ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.event.number }}-${{ env.COMPONENT }})
          SHA1=$(docker inspect -f '{{.Id}}' ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.PROMOTION }}-${{ env.COMPONENT }})

          # If different, then trigger updates
          if [[ "${SHA0}" == "${SHA1} "]]; then
            echo "::set-output name=build::true"
            echo "Image has changed"

            # Login to OpenShift and select project
            oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
            oc project ${{ secrets.OC_NAMESPACE }}
            oc delete is/${{ env.NAME }}-${{ env.PROMOTION}}-${{ env.COMPONENT }} || true
            exit 0
          fi
          echo "Image promotion not required"

      - name: Promote Backend Image
        if: steps.check.outputs.build == 'true'
        uses: shrink/actions-docker-registry-tag@v2
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}
          target: ${{ github.event.number }}-${{ env.COMPONENT }}
          tags: |
            ${{ env.PROMOTION }}-${{ env.COMPONENT }}

  # Notify when PR merged and branch = main
  merge-notification:
    name: Merge Notification
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Pre-merge update
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allow-repeats: false
          message: |
            Your Pull Request code is being promoted!  Please follow the link below.

            [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)
