name: PR Closed

on:
  pull_request:
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # Clean up OpenShift when PR closed, no conditions
  cleanup-openshift:
    name: Cleanup OpenShift
    env:
      deployment: ${{ github.event.repository.name }}-${{ github.event.number }}
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Remove OpenShift artifacts
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ vars.OC_SERVER }}
          oc project ${{ vars.OC_NAMESPACE }} # Safeguard!

          # If found, then remove
          helm status ${{ env.deployment }} && helm uninstall --no-hooks ${{ env.deployment }} || \
            echo "Not found: ${{ env.deployment }}"

          # Remove Bitnami Crunchy PVCs
          oc delete pvc data-${{ env.deployment }}-bitnami-pg-0 || \
            echo "Not found: pvc data-${{ env.deployment }}-bitnami-pg-0"

  promote-test:
    name: Promote Images
    if: github.event.pull_request.base.ref == github.event.repository.default_branch &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ github.event.number }}
          tags: test
