name: Cleanup

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  cleanup-openshift:
    name: Cleanup OpenShift
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Remove OpenShift artifacts
        run: |
          set -ex
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}

          # Remove old build runs, build pods and deployment pods
          oc delete all,pvc,secret -l app=gfp-${{ github.event.number }}

  cleanup-ghcr:
    name: Cleanup ghcr.io
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/ghcr-io-container-cleanup
      - name: Delete old packages
        uses: davahome/ghcr-cleanup@v1
        with:
            # The regular ${{ GITHUB_TOKEN }} is not enough because there is no "packages:delete" permission.
            # Create a separate token and store it as a secret (see required permissions at the bottom of this README)
            token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
            
            # Define the name of the package (e.g. "thedava/example" would be "example")
            package: greenfield-template
            
            # Define the owner (it's either literally "user" or "orgs/<Your Org>")
            owner: orgs/bcgov

            # Configure cleanup of tagged versions
            minimum_days: 1
            keep_versions: 5
            skip_tags: prod,test

            # Configure cleanup of untagged versions
            delete_untagged: 14
            keep_versions_untagged: 10

