name: PR Closed

on:
  pull_request:
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # Clean up OpenShift when PR closed, no conditions
  cleanup-openshift:
    name: Cleanup OpenShift
    env:
      name: ${{ github.event.repository.name }}-${{ github.event.number }}
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Remove OpenShift artifacts
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ vars.OC_SERVER }}
          oc project ${{ vars.OC_NAMESPACE }}

          # If found, then remove
          helm status ${{ env.name }} && helm uninstall --no-hooks ${{ env.name }} || \
            echo "Not found: ${{ env.name }}"

          # Remove Bitnami Crunchy PVCs
          oc delete pvc data-${{ github.event.repository.name }}-${{ github.event.number }}-bitnami-pg-0

  # https://github.com/bcgov-nr/action-deployer-openshift
  merge:
    name: Merge
    if: github.event.pull_request.base.ref == '${{ github.event.repository.default_branch }}' && \
      github.event.pull_request.merged == true
    needs: [tag-images]
    uses: ./.github/workflows/.merge.yml
    secrets: inherit
    with:
      promote: ${{ github.event.number }}
