name: Cleanup

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  cleanup-openshift:
    name: Cleanup OpenShift
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Remove OpenShift artifacts
        run: |
          set -ex
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}

          # Remove old build runs, build pods and deployment pods
          oc delete all,pvc,secret -l app=gfp-${{ github.event.number }}

  cleanup-ghcr:
    name: Cleanup ghcr.io
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/delete-package-versions
      - uses: actions/delete-package-versions@v3
        with:
          package-name: greenfield-template
          # min-versions-to-keep: 10
          num-old-versions-to-delete: 99
