name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/bcgov-nr/greenfield-pipeline:pr-${{ github.event.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set -ex
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}

          # Cancel any rollouts in progress
          oc rollout cancel dc/gfp-${{ github.event.number }} 2> /dev/null \
            || true && echo "No rollout in progress"

          # Process and apply deployment template
          oc process -f .pipeline/deploy.yml \
            -p SUFFIX=${{ github.event.number }} -p ENV=${{ secrets.ENV }} \
              | oc apply -f -

          # Start rollout (if necessary) and follow it
          oc rollout latest dc/gfp-${{ github.event.number }} 2> /dev/null \
            || true && echo "Rollout in progress"
          oc logs -f dc/gfp-${{ github.event.number }}

          # Get status, returns 0 if rollout is successful
          oc rollout status dc/gfp-${{ github.event.number }}
