name: Pull Request

on:
  pull_request:

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  notifier:
    name: notifier
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.2
        with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          # connection_url: ${{secrets.MAIL_CONNECTION}}
          # Required mail server address if not connection_url:
          server_address: apps.smtp.extest.gov.bc.ca
          # Server port, default 25:
          server_port: 25
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: false
          # Optional (recommended) mail server username:
          username: ""
          # Optional (recommended) mail server password:
          password: ""
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: derek.roberts@gmail.com,derek.roberts@gov.bc.ca
          # Required sender full name (address can be skipped):
          from: DoNotReploy@gov.bc.ca # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          reply_to: DoNotReploy@gov.bc.ca
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          # priority: low

  # pr-greeting:
  #   name: PR Greeting
  #   env:
  #     DOMAIN: apps.silver.devops.gov.bc.ca
  #     PREFIX: ${{ github.event.repository.name }}-${{ github.event.number }}
  #   runs-on: ubuntu-22.04
  #   permissions:
  #     pull-requests: write
  #   steps:
  #     - name: PR Greeting
  #       uses: bcgov-nr/action-pr-description-add@v0.0.2
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         add_markdown: |
  #           ---

  #           Thanks for the PR!

  #           Any successful deployments (not always required) will be available below.
  #           [Backend](https://${{ env.PREFIX }}-backend.${{ env.DOMAIN }}/) available
  #           [Frontend](https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}/) available

  #           Once merged, code will be promoted and handed off to following workflow run.
  #           [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)

  # builds:
  #   name: Builds
  #   runs-on: ubuntu-22.04
  #   permissions:
  #     packages: write
  #   strategy:
  #     matrix:
  #       package: [backend, database, frontend]
  #       include:
  #         - package: backend
  #           triggers: ('backend/')
  #         - package: database
  #           triggers: ('database/')
  #         - package: frontend
  #           triggers: ('frontend/')
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: bcgov-nr/action-builder-ghcr@v1.1.0
  #       with:
  #         package: ${{ matrix.package }}
  #         tag: ${{ github.event.number }}
  #         tag_fallback: test
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         triggers: ${{ matrix.triggers }}

  # deploys:
  #   name: Deploys
  #   needs:
  #     - builds
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       name: [backend, database, init, frontend]
  #       include:
  #         - name: backend
  #           file: backend/openshift.deploy.yml
  #           overwrite: true
  #           parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
  #         - name: database
  #           file: database/openshift.deploy.yml
  #           overwrite: false
  #         - name: frontend
  #           file: frontend/openshift.deploy.yml
  #           overwrite: true
  #           parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
  #         - name: init
  #           file: common/openshift.init.yml
  #           overwrite: false
  #   steps:
  #     - uses: bcgov-nr/action-deployer-openshift@v1.0.3
  #       with:
  #         file: ${{ matrix.file }}
  #         oc_namespace: ${{ vars.OC_NAMESPACE }}
  #         oc_server: ${{ vars.OC_SERVER }}
  #         oc_token: ${{ secrets.OC_TOKEN }}
  #         overwrite: ${{ matrix.overwrite }}
  #         penetration_test: false
  #         parameters:
  #           -p ZONE=${{ github.event.number }} -p NAME=${{ github.event.repository.name }}
  #           -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:${{ github.event.number }}
  #           ${{ matrix.parameters }}
