name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TRIGGERS: ('frontend/' 'backend/' '.github/pipeline')

jobs:
  check:
    name: Check
    outputs:
      build: ${{ steps.check.outputs.build }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check and process modified files
        id: check
        run: |
          # Fetch main to diff against
          git fetch origin main:refs/remotes/origin/master

          # Trigger build if diff matches any triggers
          TRIGGERS=${{ env.TRIGGERS }}
          while read -r check
          do
              for t in "${TRIGGERS[@]}"; do
                  if [[ "${check}" =~ "${t}" ]]
                  then
                      # Output build=true for next steps
                      echo "::set-output name=build::true"
                      echo -e "${t}\n --> ${check}\n"
                      exit 0
                  fi
              done
          done < <(git diff origin/main --name-only)
          echo "Build and deploy workflows not triggered"

  build:
    name: Build
    needs:
      - check
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          push: true
          tags: ghcr.io/bcgov/greenfield-template:pr-frontend-${{ github.event.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend/
          push: true
          tags: ghcr.io/bcgov/greenfield-template:pr-backend-${{ github.event.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  tests-frontend:
    name: Tests-Frontend
    needs:
      - check
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Tests
        run: |
          cd frontend
          npm ci
          npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.exclusions=**/test/*
            -Dsonar.sources=./src
            -Dsonar.typescript.lcov.reportPath=./coverage/lcov.info
            -Dsonar.testExecutionReportPath=./test-report.xml
          # -Dsonar.verbose=true

  tests-backend:
    name: Tests-Backend
    needs:
      - check
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Tests
        run: |
          cd backend
          npm ci
          npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.exclusions=**/test/*
            -Dsonar.sources=./src
            -Dsonar.typescript.lcov.reportPath=./coverage/lcov.info
            -Dsonar.testExecutionReportPath=./test-report.xml
          # -Dsonar.verbose=true

  codeql:
    name: CodeQL
    needs:
      - check
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Analysis
        uses: github/codeql-action/analyze@v1

  # https://github.com/snyk/snyk
  snyk:
    name: Snyk
    needs:
      - check
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-projects --severity-threshold=high

  deploy:
    name: Deploy
    needs: 
      - build
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set -eux

          # Login to OpenShift and select project
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}

          # Cancel any rollouts in progress
          oc rollout cancel dc/gfp-frontend-${{ github.event.number }} 2> /dev/null \
            || true && echo "No rollout in progress"
          
          # Remove any stale imagestreams
          oc delete is/gfp-frontend-${{ github.event.number }} 2> /dev/null \
            || true && echo "No stale imagestreams"
          oc delete is/gfp-backend-${{ github.event.number }} 2> /dev/null \
            || true && echo "No stale imagestreams"
          oc delete is/gfp-database-${{ github.event.number }} 2> /dev/null \
            || true && echo "No stale imagestreams"

          # Process and apply deployment template
          for y in .github/pipeline/deploy.*.yml
          do oc process -f ${y} -p SUFFIX=${{ github.event.number }} -p NAMESPACE=${{ secrets.NAMESPACE }} \
              | oc apply -f -
          done

          # Start rollout (if necessary) and follow it
          oc rollout latest dc/gfp-frontend-${{ github.event.number }} 2> /dev/null \
            || true && echo "Rollout in progress"
          oc logs -f dc/gfp-frontend-${{ github.event.number }}

          # Get status, returns 0 if rollout is successful
          oc rollout status dc/gfp-frontend-${{ github.event.number }}

      - name: Deployment update
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            [${{ secrets.ENV }} - Backend](https://gfp-backend-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/) deployment available
            [${{ secrets.ENV }} - Frontend](https://gfp-frontend-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/) deployment available
          allow-repeats: false

  zap:
    name: Zap
    needs:
      - check
      - deploy
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: https://gfp-${{ github.event.number }}.apps.silver.devops.gov.bc.ca/
          cmd_options: '-a'
          allow_issue_writing: false
          fail_action: false

  # trivy:
  #   name: Trivy
  #   needs:
  #     - build
  #   if: needs.check.outputs.build == 'true'
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   steps:
  #   - name: Trivy Vulnerability Scan
  #     uses: aquasecurity/trivy-action@master
  #     with:
  #       image-ref: ghcr.io/bcgov/greenfield-template:pr-${{ github.event.number }}
  #       format: table
  #       exit-code: '1'
  #       ignore-unfixed: true
  #       vuln-type: os,library
  #       severity: CRITICAL
