name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check:
    name: Check
    outputs:
      build: ${{ steps.check.outputs.build }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check and process modified files
        id: check
        run: |
          # Check git diff against build triggers
          git fetch origin main:refs/remotes/origin/master

          TRIGGERS=(
              'package.json'
              'package-lock.json'
              'Dockerfile'
              '.src/'
              '.github/workflows/'
          )

          while read -r check
          do
              for t in "${TRIGGERS[@]}"; do
                  if [[ "${check}" =~ "${t}" ]]
                  then
                      echo -e "${t}\n --> ${check}\n"
                      echo "::set-output name=build::true"
                      exit 0
                  fi
              done
          done < <(git diff origin/main --name-only)
          echo "Build and deploy workflows not triggered"

  build:
    name: Build
    needs: check
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/bcgov-nr/greenfield-pipeline:pr-${{ github.event.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    needs: 
      - check
      - build
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set -ex
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc project ${{ secrets.NAMESPACE }}

          # Cancel any rollouts in progress
          oc rollout cancel dc/gfp-${{ github.event.number }} 2> /dev/null \
            || true && echo "No rollout in progress"
          
          # Remove any stale imagestreams
          oc delete is/gfp-${{ github.event.number }} 2> /dev/null \
            || true && echo "No stale imagestreams"

          # Process and apply deployment template
          oc process -f .github/pipeline/deploy.yml -p SUFFIX=${{ github.event.number }} \
            | oc apply -f -

          # Start rollout (if necessary) and follow it
          oc rollout latest dc/gfp-${{ github.event.number }} 2> /dev/null \
            || true && echo "Rollout in progress"
          oc logs -f dc/gfp-${{ github.event.number }}

          # Get status, returns 0 if rollout is successful
          oc rollout status dc/gfp-${{ github.event.number }}

  # https://github.com/aquasecurity/trivy
  trivvy:
    name: Trivvy
    needs: 
      - check
      - build
    if: needs.check.outputs.build == 'true'
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/bcgov-nr/greenfield-pipeline:pr-${{ github.event.number }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
