name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [migrations, backend, frontend]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.0.2
        with:
          keep_versions: 50
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')

  # https://github.com/bcgov-nr/action-deployer-helm
  deploys:
    name: Deploys
    needs: [builds]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-deployer-helm@main
        with:
          params: |
            --set global.autoscaling=false
          release: ${{ github.event.number }}
          triggers: ('backend/', 'frontend/', 'migrations/')

  tests:
    name: Tests
    needs: [deploys]
    if: needs.deploys.outputs.triggered == 'true'
    uses: ./.github/workflows/.tests.yml
    with:
      target: ${{ github.event.number }}

  results:
    name: PR Results
    needs: [tests]
    if: always() && !failure()
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Workflow completed successfully!"
