name: Pull Request Opened

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-greeting:
    name: PR Greeting
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}-${{ github.event.number }}
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: PR Greeting
        uses: DerekRoberts/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---

            Thanks for the PR!

            Any successful deployments (not always required) will be available below.
            [Backend](https://${{ env.PREFIX }}-backend.${{ env.DOMAIN }}/) available
            [Frontend](https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}/) available

            Once merged, code will be promoted and handed off to following workflow run.
            [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)

  builds:
    name: Builds
    uses: bcgov/nr-quickstart-helpers/.github/workflows/_build.yml@v0.0.2
    permissions:
      packages: write
    strategy:
      matrix:
        component: [backend, database, frontend]
        include:
          - component: backend
            triggers: ('backend/')
          - component: database
            triggers: ('database/')
          - component: frontend
            triggers: ('frontend/')
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      component: ${{ matrix.component }}
      img_build: ${{ github.event.number }}
      img_fallback: test
      triggers: ${{ matrix.triggers }}

  deploys:
    name: Deploys
    needs:
      - builds
    uses: bcgov/nr-quickstart-helpers/.github/workflows/_deploy.yml@main
    strategy:
      matrix:
        component: [init, backend, database, frontend]
        include:
          - component: init
            overwrite: false
            template_file: common/openshift.init.yml
            template_vars: -p ZONE=${{ github.event.number }}
          - component: database
            overwrite: false
            template_file: database/openshift.deploy.yml
            template_vars: -p ZONE=${{ github.event.number }}
              -p PROMOTE=${{ github.repository }}/database:${{ github.event.number }}
          - component: backend
            overwrite: true
            template_file: backend/openshift.deploy.yml
            template_vars:
              -p ZONE=${{ github.event.number }} -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
              -p PROMOTE=${{ github.repository }}/backend:${{ github.event.number }}
          - component: frontend
            overwrite: true
            template_file: frontend/openshift.deploy.yml
            template_vars:
              -p ZONE=${{ github.event.number }} -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
              -p PROMOTE=${{ github.repository }}/frontend:${{ github.event.number }}
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_server: ${{ secrets.OC_SERVER }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      component: ${{ matrix.component }}
      overwrite: ${{ matrix.overwrite }}
      penetration_test: false
      template_file: ${{ matrix.template_file }}
      template_vars: ${{ matrix.template_vars }}

  tests:
    name: Unit Tests and Analysis
    uses: bcgov/nr-quickstart-helpers/.github/workflows/_unit-tests.yml@main
    strategy:
      matrix:
        dir: [backend, frontend]
        include:
          - dir: backend
            sonar_projectKey: bcgov_nr-quickstart-typescript_backend
            sonar_token: SONAR_TOKEN_BACKEND
          - dir: frontend
            sonar_projectKey: bcgov_nr-quickstart-typescript_frontend
            sonar_token: SONAR_TOKEN_FRONTEND
    secrets:
      sonar_token: ${{ secrets[matrix.sonar_token] }}
    with:
      dir: ${{ matrix.dir }}
      sonar_args: >
        -Dsonar.organization=bcgov-sonarcloud
        -Dsonar.projectKey=${{ matrix.sonar_projectKey }}
      test_cmd: |
        npm ci
        npm run test:cov
