name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: OpenShift Build
        run: |
          set -ex

          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }}
          oc cancel-build bc/greenfield-pipeline
          oc start-build bc/greenfield-pipeline --follow
          LATEST=$(oc get bc/greenfield-pipeline -o 'jsonpath={.status.lastVersion}')
          RESULT=$(oc get build/greenfield-pipeline-${LATEST})
          if [ "${RESULT}" != "Success" ]; then
            echo "Build failed or cancelled"
            exit 1
          fi
          echo "Build successful"
