{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels: {{- include "selectorLabels" . | nindent 4 }}
data:
  databasePassword: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  databaseUser: {{  .Values.global.secrets.databaseUser| default "postgres" | b64enc | quote }}
  databaseName: {{  .Values.global.secrets.databaseName| default "postgres" | b64enc | quote }}
{{- end }}
